# Font Settings
[font]
size = 11
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

# Keyboard Bindings
[keyboard]
bindings = [
  # Control+Shift+N => New Window
  { key = "n", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# Transparent Background
[window]
opacity = 0.95

# Colours
[colors.primary]
background = '#000000'
foreground = '#dddddd'

# Cursor colors
[colors.cursor]
cursor = '#dddddd'
text = '#000000'

# Normal colors
[colors.normal]
black = '#000000'
red = '#ff2c0b'
green = '#0be20b'
yellow = '#fffb00'
blue = '#33aaff'
magenta = '#c930c7'
cyan = '#00c5c7'
white = '#c7c7c7'

# Bright colors
[colors.bright]
black = '#7f8c8d'
red = '#ff6d67'
green = '#5ff967'
yellow = '#fefb67'
blue = '#62bdff'
magenta = '#ff76ff'
cyan = '#5ffdff'
white = '#fffeff'

# Selection colors
[colors.selection]
background = '#dddddd'
text = '#000000'

# Startup Application
#[shell]
#program = "/usr/bin/bash"
#args = ["-l", "-c", "zellij"]
